// <auto-generated />
using System;
using ApexLog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApexLog.Infrastructure.Migrations
{
    [DbContext(typeof(ApexLogDbContext))]
    partial class ApexLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApexLog.Domain.Entities.TelemetryPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EngineTempC")
                        .HasColumnType("double precision");

                    b.Property<int>("Rpm")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedKmh")
                        .HasColumnType("integer");

                    b.Property<double>("ThrottlePosition")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("telemetry_points", (string)null);
                });

            modelBuilder.Entity("ApexLog.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("ApexLog.Domain.Entities.TelemetryPoint", b =>
                {
                    b.HasOne("ApexLog.Domain.Entities.Trip", null)
                        .WithMany("TelemetryPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApexLog.Domain.Entities.Trip", b =>
                {
                    b.Navigation("TelemetryPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
